name: Daily run update.py

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tracker/requirements.txt

    - name: Run update.py
      run: python tracker/update.py

    - name: Move files to tracker directory
      run: |
        mv ipv4.txt tracker/
        mv ipv6.txt tracker/
        mv host.conf tracker/

    - name: Commit and push
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add tracker/ipv4.txt tracker/ipv6.txt tracker/host.conf
        git commit -m "Update"
        git push
