name: Daily run update.py

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run update.py
      run: python tracker/update.py

    - name: Commit and push
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your-email@example.com'
        git add tracker/ipv4.txt tracker/ipv6.txt tracker/host.conf
        git commit -m "Update files"
        git push
